[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
port = 8080

[deploy.env]
NODE_ENV = "production"
PORT = "8080"
POCKETBASE_URL = "https://pocketbase-production-040c.up.railway.app"
WEBAPP_URL = "https://orderapp-production.up.railway.app" 