[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.env]
NODE_ENV = "production"
POCKETBASE_URL = "http://localhost:8090" 